---
dotfiles_repo: "https://github.com/benjwrdill/dotfiles.git"
dotfiles_repo_accept_hostkey: no
dotfiles_repo_local_destination: "~/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .vimrc
  - .tmux.conf
  - .zshrc
